### ISSUE TITLE
Compilation fails because of double use of Namespace Dumpert

### ISSUE THREAD

**Issue by tijldeneut** [jfmaes/SharpHandler#1]

**Comment by jfmaes** [comment]
can you retry to compile by repulling the repo and following the compile instructions? :) 
there was indeed a fuck up on my end , pushed the wrong codebase but should be fixed now

**Comment by tijldeneut** [comment]
Yes, the new codebase fixes the issues completely. Compilation instructions not even needed now (VS2019, just double click the sln file and press F5).
